# Generated by Django 5.0.4 on 2024-04-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaPlay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='track_id',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
