# Generated by Django 5.0.4 on 2024-05-06 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaPlay', '0002_remove_song_id_song_track_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=20)),
                ('profile_pic', models.ImageField(upload_to='user_profile_pic')),
                ('member', models.CharField(default='GUEST', max_length=100)),
            ],
        ),
    ]
