# Generated by Django 5.0.4 on 2024-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaPlay', '0003_listener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='name',
        ),
        migrations.AddField(
            model_name='listener',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listener',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listener',
            name='username',
            field=models.SlugField(default=''),
        ),
    ]
