# Generated by Django 5.0.4 on 2024-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaPlay', '0006_alter_listener_address_alter_listener_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
