# Generated by Django 5.0.4 on 2024-05-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaPlay', '0007_alter_listener_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaPlay.listener')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaPlay.song')),
            ],
        ),
    ]
