# Generated by Django 5.0.6 on 2024-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaPlay', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
